### PR TITLE
MySQL2

### PR DESCRIPTION
**Pull request by cwise**
I added MySQL2 support which was incredibly minimal - the new drivers doesn't require a a free of fetched columns. I didn't add any tests, but figured you might end up wanting to simply make the change from scratch yourself. Might be nice if there was a way to add a level of abstraction for the specific driver and column types.

### CODE REVIEW

**Comment by pdeffendol** [comment]
I'll merge this in provided there is a test suite that passes for the new adapter.  I'm not a MySQL user at all, but copying the test data and specs from the "old" MySQL adapter should be adequate.

**Comment by sozialhelden** [comment]
I saw that tests have been provided. Will mysql2 support be pulled in?

Thx, that would be awesome!

**Comment by pdeffendol** [comment]
I've pulled in the changes and released version 1.2.0

**Comment by cwise** [comment]
Cool! I feel useful in making my first open source contribution. Small I know, but at least I know the routine. Thanks for a great gem!

**Pull request merged**
