### PR TITLE
Added JDBC MySQL Adapter and Other Improvements

### PR DESCRIPTION
**Pull request by panthomakos**
This pull request include a lot of updates/upgrades, including some configuration changes such as adding a Gemfile for bundler support and updating the gemspec.  I found that these upgrades make contributing and getting setup much faster and easier. The initial intent of my commit was to add the jdbcmysql adapter, but I realized there was a lot of code duplication and decided to do some cleanup as well. I have verified that all tests pass (spec:mysql, spec:mysql2, spec:jdbcmysql, spec:postgresql). The changes in this pull include:
- Upgraded the gem structure to use a more generic rubygems gemspec.
- Added a Gemfile to install development dependencies for easier testing.
- Added bundler require to simplify code in specs and lib.
- Updated the README.rdoc file to include testing information.
- Added support for the jdbcmysql adapter.
- Consolidated common mysql code and tests to conform to DRY principles. There was a lot of replicated code in tests and mysql related files that is now shared in modules.
- Upgraded tests to be compliant with the new rspec format.
- Upgraded tests to be compliant with the new SchemaDumper format.
- Removed jeweler related gemspec that was hacked into the Rakefile.
- Added a .gitignore file with commonly ignored files.

Please let me know if you have any questions/comments/suggestions.

P.S: You can now install all dependencies using `bundle install`. You can now build a .gem file using `gem build spatial_adapter.gemspec` or `rake install` and publish it using `gem push spatial_adapter-1.2.0.gem`. More information about these commands can be found [here](https://rubygems.org).

### CODE REVIEW

**Comment by pdeffendol** [comment]
Wow, this is a lot to digest all at once.  Separate commits would have been more appropriate.  I'll see what I can do, but it may take a while.

**Comment by panthomakos** [comment]
I've added some inline notes to each file to better describe what I did.  Sorry again for the large commit.  I was finding it difficult to run tests and duplicate code so I kind of got dragged down a larger refactoring path. Please let me know if there is anything I can clarify.

**Comment by pdeffendol** [comment]
I've pulled in all your changes via cherry-picking so as to avoid one large commit.  I did make some very minor changes, so apologies if it doesn't merge cleanly.

**Comment by panthomakos** [comment]
Only had conflicts in README.rdoc, version and the raw jdbcmysql test file but they were easy to cleanup. Thanks, and sorry again for the massive pull request.

**Pull request closed without merging**
